ADD plan-debug and apply-debug; ADD auto-remove docker containers after shutdown

diff --git a/tc b/tc
--- a/tc
+++ b/tc
@@ -80,7 +80,7 @@ runTerraform() {
 runTerraformInternal() {
     local TF_ARGS=$@
 
-    docker run -ti \
+    docker run --rm -ti \
         --entrypoint '' \
         -v "${BASE_DIR}":"${BASE_DIR}" \
         -v ~/.aws:/root/.aws \
@@ -101,7 +101,7 @@ runTerraformInteractive() {
 
     echo -e "${YC} >>> Command: ${RC}docker run -ti --entrypoint '' -v \"${BASE_DIR}\":\"${BASE_DIR}\" -v ~/.aws:/root/.aws -v ~/.ssh:/root/.ssh -e AWS_PROFILE=${AWS_PROFILE} ${ENV_VARS_FILE_DOCKER_PARAM} -w=${PROJECT_DIR} hashicorp/terraform:${TF_VERSION} /bin/sh${NC}"
 
-    docker run -ti \
+    docker run --rm -ti \
         --entrypoint '' \
         -v "${BASE_DIR}":"${BASE_DIR}" \
         -v ~/.aws:/root/.aws \
@@ -257,7 +257,7 @@ function getYamlConfigValue {
 
 ACTION=$1
 case "${ACTION}" in
-    'plan' | 'apply' | 'workspaces' | 'run' | 'shell' )
+    'plan' | 'plan-debug' | 'apply' | 'apply-debug' | 'workspaces' | 'run' | 'shell' )
         ;;
     'help')
         echo "${HELP_STRING}"
@@ -365,6 +365,41 @@ case "${ACTION}" in
         echo -e "\n${YC} >>> TF plan:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC} / tfvar ${RC}${TFVARS_FILENAME}${NC}: was generated plan ${RC}${TF_PLAN_FILENAME}${NC}\n${YC} >>> ${NC}(${TF_PLAN_FILE})\n"
         exit;;
 
+    # TODO re-use plan action
+    'plan-debug')
+        echo -e "${YC} >>> Running in ${RC}DEBUG${YC} mode (without init backend, format check and validation)!${NC}"
+        echo -e "\n------------------------------------------------------------------------\n"
+
+        # TF workspaces
+        selectWorkspace
+
+        # TF tfvar
+        echo -e "${YC} >>> Searching for ${RC}tfvar${YC} file ... ${NC}"
+        if [ -z "${PROJECT_TFVAR}" ]; then
+            # no pre-configured tfvar
+            echo -e "${YC} >>> No TFVAR filename was found at the config, so will try current workspace '${RC}${CURRENT_WORKSPACE}${YC}' as a TFVAR name${NC}"
+            TFVARS_FILENAME="$( askIfNotExistsTfVarsFile "${CURRENT_WORKSPACE}" )"
+            TFVARS_COMMAND_PARAM="-var-file=${TFVARS_FILENAME}.tfvars"
+        elif [ "${PROJECT_TFVAR}" = '-' ]; then
+            # pre-configured to skip tfvar
+            echo -e "${YC} >>> Skipping TFVAR because '${RC}${PROJECT_TFVAR}${YC}' was found in alias config${NC}"
+            TFVARS_FILENAME="-"
+            TFVARS_COMMAND_PARAM=""
+        else
+            # pre-configured tfvar
+            echo -e "${YC} >>> TFVAR filename '${RC}${PROJECT_TFVAR}${YC}' was found in alias config${NC}"
+            TFVARS_FILENAME="$( askIfNotExistsTfVarsFile "${PROJECT_TFVAR}" )"
+            TFVARS_COMMAND_PARAM="-var-file=${TFVARS_FILENAME}.tfvars"
+        fi
+
+        # TF plan
+        echo -e "\n------------------------------------------------------------------------\n"
+        echo -e "${YC} >>> Building TF plan:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC} / tfvar ${RC}${TFVARS_FILENAME}${NC}"
+        echo -e "\n------------------------------------------------------------------------\n"
+        runTerraform plan ${TFVARS_COMMAND_PARAM} -out=${TF_PLAN_FILENAME}
+        echo -e "\n${YC} >>> TF plan:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC} / tfvar ${RC}${TFVARS_FILENAME}${NC}: was generated plan ${RC}${TF_PLAN_FILENAME}${NC}\n${YC} >>> ${NC}(${TF_PLAN_FILE})\n"
+        exit;;
+
     'apply')
         runTerraformInit
 
@@ -395,7 +430,40 @@ case "${ACTION}" in
         echo -e "\n${YC} >>> TF apply:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}: applied plan ${RC}${TF_PLAN_FILENAME}${NC}"
         echo -e "${YC} >>> ${NC}Plan ${YC}${TF_PLAN_FILE}${NC} has been ${RC}removed${NC}\n"
         exit;;
-    
+
+    # TODO re-use apply action
+    'apply-debug')
+        echo -e "${YC} >>> Running in ${RC}DEBUG${YC} mode (without init backend, format check and validation)!${NC}"
+        echo -e "\n------------------------------------------------------------------------\n"
+
+        # TF workspaces
+        selectWorkspace
+
+        # check TF plan
+        if [ ! -f "${TF_PLAN_FILE}" ]; then
+            echo -e "${RC}Error${NC}: TF plan file ${YC}${TF_PLAN_FILE}${NC} does not exists. \nPlease build TF plan first"
+            exit 10
+        fi
+
+        # TF apply
+        echo -e "\n------------------------------------------------------------------------\n"
+        echo -e "${YC} >>> Applying TF plan:${NC} ${RC}${TF_PLAN_FILENAME}${NC} / alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}"
+        echo -e "${YC} >>> ${NC}File ${YC}${TF_PLAN_FILE}${NC} was modified ${YC}$( humanTimeSinceFileModified "${TF_PLAN_FILE}" ) ago${NC}"
+        echo -e "\n------------------------------------------------------------------------\n"
+
+        read -p "Are you sure that you want to apply ${CURRENT_WORKSPACE}? To approve print 'yes': " APPLY_APPROVE
+        if [ ! "${APPLY_APPROVE}" = 'yes' ]; then
+            echo -e "${YC} >>> Exiting ... ${NC}\n"
+            exit 0
+        fi
+
+        runTerraform apply ${TF_PLAN_FILENAME}
+        rm ${TF_PLAN_FILE}
+
+        echo -e "\n${YC} >>> TF apply:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}: applied plan ${RC}${TF_PLAN_FILENAME}${NC}"
+        echo -e "${YC} >>> ${NC}Plan ${YC}${TF_PLAN_FILE}${NC} has been ${RC}removed${NC}\n"
+        exit;;
+
     *)
         echo -e "${RC}Error:${NC} ooops, catch all for invalid action ${ACTION}"
         exit 1;;
